### ISSUE TITLE
GoButton.Click(); fails in HuddlePageObjectsAppDesignPattern of WebDriver-Series

### ISSUE THREAD

**Issue by ashotav** [AutomateThePlanet/AutomateThePlanet-Learning-Series#10]
First, thanks for such a vastly rich resources, @angelovstanton !

Persistent issue is in this part:
`

    public override string Url => @"http://www.bing.com/";
    public void Search(string textToType)
    {
        SearchBox.Clear();
        SearchBox.SendKeys(textToType);
        GoButton.Click();
     }
`
Go Button does not become clickable as Click() throws
Result Message:	
Test method HuddlePageObjectsElementsStringProperties.BingTests.UseApp_SearchTextInBing_UseElementsDirectly threw exception: 
OpenQA.Selenium.ElementNotInteractableException: Element input id="sb_form_go" name="search" type="submit" **could not be scrolled into view**
Tried a few precautions before GoButton.Click(); like

`      var wait = new WebDriverWait(WrappedDriver, TimeSpan.FromSeconds(8));
        wait.Until(ExpectedConditions.ElementExists(By.Id("sb_form_go")));
        wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("sb_form_go")));`
while ElementExists condition is true, the ElementToBeClickable is never met.

Attached is [packages.config.txt](https://github.com/AutomateThePlanet/AutomateThePlanet-Learning-Series/files/4602006/packages.config.txt)
I'd appreciate any advice!

**Comment by angelovstanton** [comment]
Sorry for my late answer. I didn't receive any notifications about the issue; not answering wasn't intentional. I can suggest a few things. First, try to execute the test in a different browser or even a different browser version. I guess Bing made some updates to their website and broke the example. Anyhow, a second thing may be to use Actions class to MoveTo to the element or use JavaScript to do so.
